apiVersion: v1
kind: Namespace
metadata:
  name: minio

---

apiVersion: v1
data:
  MINIO_DEFAULT_BUCKETS: datasets,reports
kind: ConfigMap
metadata:
  name: settings

---

apiVersion: v1
data:
  MINIO_ROOT_PASSWORD: amFob2RrYTEyMw==
  MINIO_ROOT_USER: YWRtaW4=
kind: Secret
metadata:
  name: app-secrets

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
  # namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - image: bitnami/minio
        name: minio
        envFrom:
        - configMapRef:
            name: settings
        - secretRef:
            name: app-secrets

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio-svc
  # namespace: application
spec:
  ports:
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 30000
  - name: www
    port: 9001
    protocol: TCP
    targetPort: 9001
    nodePort: 30001
  selector:
    app: minio
  type: NodePort


