apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg16
  labels:
    app: pg16
    # namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg16
  template:
    metadata:
      labels:
        app: pg16
    spec:
      containers:
      - image: postgres:16-alpine
        name: postgres16
        # ports:
        # - containerPort: 5432
        envFrom:
        - configMapRef:
            name: app-settings
        - secretRef:
            name: app-credentials
        # env:
        # - name: TZ
        #   value: Europe/Bratislava
        # - name: MYSQL_ROOT_PASSWORD
        #   value: rado
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pg16

---

apiVersion: v1
kind: Service
metadata:
  name: pg16
  labels:
    app: pg16
    # namespace: application
spec:
  ports:
  - name: www
    port: 5432
    protocol: TCP
    # targetPort: 80
    # nodePort: 30000
  selector:
    app: pg16
    # type: NodePort

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg16
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  capacity: # how much
    storage: 300Mi
  accessModes: # additional params
  - ReadWriteOnce
  hostPath: # volume type params
    path: "/mnt/pg16"
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg16
  # namespace: application
  labels:
    app: pg16
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes: # params
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
