apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: adminer
  name: adminer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adminer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: adminer
    spec:
      containers:
      - image: adminer
        name: adminer
        resources: {}
status: {}
