apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: www
          mountPath: /usr/share/nginx/html
        - name: cache
          mountPath: /cache
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 100Mi
      - name: www
        hostPath:
          path: /data
          type: DirectoryOrCreate
      - name: cache
        persistentVolumeClaim:
          claimName: volume-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
