apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adminer
  name: wp-adminer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adminer
  strategy: {}
  template:
    metadata:
      labels:
        app: adminer
        tier: frontend
        env: dev
    spec:
      containers:
      - image: adminer
        name: adminer
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: adminer
  name: wp-adminer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31500
  selector:
    app: adminer
  type: NodePort
status:
  loadBalancer: {}
