apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-app
  name: wp-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wp-app
  strategy: {}
  template:
    metadata:
      labels:
        app: wp-app
        tier: frontend
        env: prod
        customer: tuke
    spec:
      containers:
      - image: wordpress
        name: wordpress
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-app
  name: wp-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: wp-app
  type: LoadBalancer
status:
  loadBalancer: {}
