apiVersion: v1
kind: Namespace
metadata:
  name: wordpress

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: wp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy: {}
  template:
    metadata:
      labels:
        app: db
        tier: backend
        env: prod
        customer: tuke
    spec:
      containers:
      - image: mariadb:10 # mysql
        name: mariadb
        resources: {}
        env:
        - name: TZ
          value: Europe/Bratislava
        - name: MYSQL_ROOT_PASSWORD
          value: top.secret
        - name: MYSQL_PASSWORD
          value: end321
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wpuser
        # envFrom:
        # - configMapRef:
        #     name: settings

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adminer
  name: wp-adminer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adminer
  strategy: {}
  template:
    metadata:
      labels:
        app: adminer
        tier: frontend
        env: dev
    spec:
      containers:
      - image: adminer
        name: adminer
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: adminer
  name: wp-adminer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31500
  selector:
    app: adminer
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-app
  name: wp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp-app
  strategy: {}
  template:
    metadata:
      labels:
        app: wp-app
        tier: frontend
        env: prod
        customer: tuke
    spec:
      containers:
      - image: wordpress
        name: wordpress
        resources: {}
        env:
        - name: WORDPRESS_DB_HOST
          value: wp-db
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: wpuser
        - name: WORDPRESS_DB_PASSWORD
          value: end321
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-app
  name: wp-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: wp-app
  type: LoadBalancer
status:
  loadBalancer: {}
