apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wp-app
  name: wp-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: wp-app
  type: LoadBalancer
status:
  loadBalancer: {}
