apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
      # selector:
      #   matchLabels:
      #     app: nginx

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-wp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  # selector:
  #   matchLabels:
  #     app: nginx

